CREATE TABLE user(
	id SERIAL NOT NULL PRIMARY KEY,
	username VARCHAR(20) NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL
);

CREATE TABLE event(
	id SERIAL NOT NULL PRIMARY KEY,
	caption VARCHAR(40) NOT NULL,
	description VARCHAR(240),
	timestamp TIMESTAMP NOT NULL DEFAULT now(),
	location VARCHAR(20) NOT NULL,
	photo VARCHAR(50),
	username VARCHAR(20) NOT NULL,
);

CREATE TABLE user_event(
	id SERIAL NOT NULL PRIMARY KEY,
	uid SERIAL NOT NULL REFERENCES user(id),
	eid SERIAL NOT NULL REFERENCES event(id)
);

CREATE TABLE tag(
	id SERIAL NOT NULL PRIMARY KEY,
	eid SERIAL NOT NULL REFERENCES event(id),
	value VARCHAR(30) NOT NULL
);