/*
 * This file is generated by jOOQ.
 */
package io.pet.database.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comment implements VertxPojo, Serializable {

    private static final long serialVersionUID = -680779081;

    private Integer       id;
    private Integer       eid;
    private LocalDateTime posted;
    private Integer       uid;
    private String        details;
    private Short         rating;

    public Comment() {}

    public Comment(Comment value) {
        this.id = value.id;
        this.eid = value.eid;
        this.posted = value.posted;
        this.uid = value.uid;
        this.details = value.details;
        this.rating = value.rating;
    }

    public Comment(
        Integer       id,
        Integer       eid,
        LocalDateTime posted,
        Integer       uid,
        String        details,
        Short         rating
    ) {
        this.id = id;
        this.eid = eid;
        this.posted = posted;
        this.uid = uid;
        this.details = details;
        this.rating = rating;
    }

    public Integer getId() {
        return this.id;
    }

    public Comment setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getEid() {
        return this.eid;
    }

    public Comment setEid(Integer eid) {
        this.eid = eid;
        return this;
    }

    public LocalDateTime getPosted() {
        return this.posted;
    }

    public Comment setPosted(LocalDateTime posted) {
        this.posted = posted;
        return this;
    }

    public Integer getUid() {
        return this.uid;
    }

    public Comment setUid(Integer uid) {
        this.uid = uid;
        return this;
    }

    public String getDetails() {
        return this.details;
    }

    public Comment setDetails(String details) {
        this.details = details;
        return this;
    }

    public Short getRating() {
        return this.rating;
    }

    public Comment setRating(Short rating) {
        this.rating = rating;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Comment (");

        sb.append(id);
        sb.append(", ").append(eid);
        sb.append(", ").append(posted);
        sb.append(", ").append(uid);
        sb.append(", ").append(details);
        sb.append(", ").append(rating);

        sb.append(")");
        return sb.toString();
    }

    public Comment(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public Comment fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getInteger("id"));
        setEid(json.getInteger("eid"));
        setPosted(json.getString("posted")==null?null:LocalDateTime.parse(json.getString("posted")));
        setUid(json.getInteger("uid"));
        setDetails(json.getString("details"));
        setRating(json.getInteger("rating")==null?null:json.getInteger("rating").shortValue());
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("eid",getEid());
        json.put("posted",getPosted()==null?null:getPosted().toString());
        json.put("uid",getUid());
        json.put("details",getDetails());
        json.put("rating",getRating());
        return json;
    }

}
