/*
 * This file is generated by jOOQ.
 */
package io.pet.database.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comment implements VertxPojo, Serializable {

    private static final long serialVersionUID = -1798280166;

    private Integer   id;
    private Integer   eid;
    private Timestamp timestamp;
    private Integer   uid;
    private String    details;

    public Comment() {}

    public Comment(Comment value) {
        this.id = value.id;
        this.eid = value.eid;
        this.timestamp = value.timestamp;
        this.uid = value.uid;
        this.details = value.details;
    }

    public Comment(
        Integer   id,
        Integer   eid,
        Timestamp timestamp,
        Integer   uid,
        String    details
    ) {
        this.id = id;
        this.eid = eid;
        this.timestamp = timestamp;
        this.uid = uid;
        this.details = details;
    }

    public Integer getId() {
        return this.id;
    }

    public Comment setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getEid() {
        return this.eid;
    }

    public Comment setEid(Integer eid) {
        this.eid = eid;
        return this;
    }

    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    public Comment setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    public Integer getUid() {
        return this.uid;
    }

    public Comment setUid(Integer uid) {
        this.uid = uid;
        return this;
    }

    public String getDetails() {
        return this.details;
    }

    public Comment setDetails(String details) {
        this.details = details;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Comment (");

        sb.append(id);
        sb.append(", ").append(eid);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(uid);
        sb.append(", ").append(details);

        sb.append(")");
        return sb.toString();
    }

    public Comment(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public Comment fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getInteger("id"));
        setEid(json.getInteger("eid"));
        // Omitting unrecognized type java.sql.Timestamp for column timestamp!
        setUid(json.getInteger("uid"));
        setDetails(json.getString("details"));
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("eid",getEid());
        // Omitting unrecognized type java.sql.Timestamp for column timestamp!
        json.put("uid",getUid());
        json.put("details",getDetails());
        return json;
    }

}
