/*
 * This file is generated by jOOQ.
 */
package io.pet.spooch.database.tables.daos;


import io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO;
import io.pet.spooch.database.tables.Event;
import io.pet.spooch.database.tables.records.EventRecord;
import io.pet.spooch.jooq.types.Point;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;


import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventDao extends AbstractReactiveVertxDAO<EventRecord, io.pet.spooch.database.tables.pojos.Event, Integer, Future<List<io.pet.spooch.database.tables.pojos.Event>>, Future<io.pet.spooch.database.tables.pojos.Event>, Future<Integer>, Future<Integer>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<EventRecord,io.pet.spooch.database.tables.pojos.Event,Integer> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the POSTGREs types.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public EventDao(Configuration configuration, io.reactiverse.pgclient.PgClient delegate) {
        super(Event.EVENT, io.pet.spooch.database.tables.pojos.Event.class, new ReactiveClassicQueryExecutor<EventRecord,io.pet.spooch.database.tables.pojos.Event,Integer>(configuration,delegate,io.pet.spooch.database.tables.mappers.RowMappers.getEventMapper()));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(io.pet.spooch.database.tables.pojos.Event object) {
        return object.getId();
    }

    /**
     * Find records that have <code>uid IN (values)</code> asynchronously
     */
    public Future<List<io.pet.spooch.database.tables.pojos.Event>> findManyByUid(List<Integer> values) {
        return findManyByCondition(Event.EVENT.UID.in(values));
    }

    /**
     * Find records that have <code>caption IN (values)</code> asynchronously
     */
    public Future<List<io.pet.spooch.database.tables.pojos.Event>> findManyByCaption(List<String> values) {
        return findManyByCondition(Event.EVENT.CAPTION.in(values));
    }

    /**
     * Find records that have <code>description IN (values)</code> asynchronously
     */
    public Future<List<io.pet.spooch.database.tables.pojos.Event>> findManyByDescription(List<String> values) {
        return findManyByCondition(Event.EVENT.DESCRIPTION.in(values));
    }

    /**
     * Find records that have <code>posted IN (values)</code> asynchronously
     */
    public Future<List<io.pet.spooch.database.tables.pojos.Event>> findManyByPosted(List<LocalDateTime> values) {
        return findManyByCondition(Event.EVENT.POSTED.in(values));
    }

    /**
     * Find records that have <code>location IN (values)</code> asynchronously
     */
    public Future<List<io.pet.spooch.database.tables.pojos.Event>> findManyByLocation(List<Point> values) {
        return findManyByCondition(Event.EVENT.LOCATION.in(values));
    }

    /**
     * Find records that have <code>photo IN (values)</code> asynchronously
     */
    public Future<List<io.pet.spooch.database.tables.pojos.Event>> findManyByPhoto(List<String> values) {
        return findManyByCondition(Event.EVENT.PHOTO.in(values));
    }

    /**
     * Find records that have <code>category IN (values)</code> asynchronously
     */
    public Future<List<io.pet.spooch.database.tables.pojos.Event>> findManyByCategory(List<String> values) {
        return findManyByCondition(Event.EVENT.CATEGORY.in(values));
    }

    @Override
    public ReactiveClassicQueryExecutor<EventRecord,io.pet.spooch.database.tables.pojos.Event,Integer> queryExecutor(){
        return (ReactiveClassicQueryExecutor<EventRecord,io.pet.spooch.database.tables.pojos.Event,Integer>) super.queryExecutor();
    }
}
