/*
 * This file is generated by jOOQ.
 */
package io.pet.database;


import io.pet.database.tables.Comment;
import io.pet.database.tables.Event;
import io.pet.database.tables.Tag;
import io.pet.database.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 531823089;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.comment</code>.
     */
    public final Comment COMMENT = io.pet.database.tables.Comment.COMMENT;

    /**
     * The table <code>public.event</code>.
     */
    public final Event EVENT = io.pet.database.tables.Event.EVENT;

    /**
     * The table <code>public.tag</code>.
     */
    public final Tag TAG = io.pet.database.tables.Tag.TAG;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = io.pet.database.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.COMMENT_EID_SEQ,
            Sequences.COMMENT_ID_SEQ,
            Sequences.COMMENT_UID_SEQ,
            Sequences.EVENT_ID_SEQ,
            Sequences.EVENT_UID_SEQ,
            Sequences.TAG_EID_SEQ,
            Sequences.TAG_ID_SEQ,
            Sequences.USER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Comment.COMMENT,
            Event.EVENT,
            Tag.TAG,
            User.USER);
    }
}
