/*
 * This file is generated by jOOQ.
 */
package io.pet.database;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.comment_eid_seq</code>
     */
    public static final Sequence<Integer> COMMENT_EID_SEQ = new SequenceImpl<Integer>("comment_eid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.comment_id_seq</code>
     */
    public static final Sequence<Integer> COMMENT_ID_SEQ = new SequenceImpl<Integer>("comment_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.comment_uid_seq</code>
     */
    public static final Sequence<Integer> COMMENT_UID_SEQ = new SequenceImpl<Integer>("comment_uid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.event_id_seq</code>
     */
    public static final Sequence<Integer> EVENT_ID_SEQ = new SequenceImpl<Integer>("event_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.event_uid_seq</code>
     */
    public static final Sequence<Integer> EVENT_UID_SEQ = new SequenceImpl<Integer>("event_uid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.tag_eid_seq</code>
     */
    public static final Sequence<Integer> TAG_EID_SEQ = new SequenceImpl<Integer>("tag_eid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.tag_id_seq</code>
     */
    public static final Sequence<Integer> TAG_ID_SEQ = new SequenceImpl<Integer>("tag_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.user_id_seq</code>
     */
    public static final Sequence<Integer> USER_ID_SEQ = new SequenceImpl<Integer>("user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
