/*
 * This file is generated by jOOQ.
 */
package io.pet.spooch.database;


import io.pet.spooch.database.tables.Comment;
import io.pet.spooch.database.tables.Event;
import io.pet.spooch.database.tables.Tag;
import io.pet.spooch.database.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COMMENT_PKEY = Indexes0.COMMENT_PKEY;
    public static final Index EVENT_PKEY = Indexes0.EVENT_PKEY;
    public static final Index TAG_PKEY = Indexes0.TAG_PKEY;
    public static final Index USER_PKEY = Indexes0.USER_PKEY;
    public static final Index USER_USERNAME_KEY = Indexes0.USER_USERNAME_KEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index COMMENT_PKEY = Internal.createIndex("comment_pkey", Comment.COMMENT, new OrderField[] { Comment.COMMENT.ID }, true);
        public static Index EVENT_PKEY = Internal.createIndex("event_pkey", Event.EVENT, new OrderField[] { Event.EVENT.ID }, true);
        public static Index TAG_PKEY = Internal.createIndex("tag_pkey", Tag.TAG, new OrderField[] { Tag.TAG.ID }, true);
        public static Index USER_PKEY = Internal.createIndex("user_pkey", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_USERNAME_KEY = Internal.createIndex("user_username_key", User.USER, new OrderField[] { User.USER.USERNAME }, true);
    }
}
