/*
 * This file is generated by jOOQ.
 */
package io.pet.spooch.database;


import io.pet.spooch.database.tables.Comment;
import io.pet.spooch.database.tables.Event;
import io.pet.spooch.database.tables.Eventsource;
import io.pet.spooch.database.tables.Tag;
import io.pet.spooch.database.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1725762410;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.comment</code>.
     */
    public final Comment COMMENT = io.pet.spooch.database.tables.Comment.COMMENT;

    /**
     * The table <code>public.event</code>.
     */
    public final Event EVENT = io.pet.spooch.database.tables.Event.EVENT;

    /**
     * The table <code>public.eventsource</code>.
     */
    public final Eventsource EVENTSOURCE = io.pet.spooch.database.tables.Eventsource.EVENTSOURCE;

    /**
     * The table <code>public.tag</code>.
     */
    public final Tag TAG = io.pet.spooch.database.tables.Tag.TAG;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = io.pet.spooch.database.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Comment.COMMENT,
            Event.EVENT,
            Eventsource.EVENTSOURCE,
            Tag.TAG,
            User.USER);
    }
}
