/*
 * This file is generated by jOOQ.
 */
package io.pet.spooch.database.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tag implements VertxPojo, Serializable {

    private static final long serialVersionUID = -495822618;

    private Integer id;
    private Integer eid;
    private String  value;
    private String  event;

    public Tag() {}

    public Tag(Tag value) {
        this.id = value.id;
        this.eid = value.eid;
        this.value = value.value;
        this.event = value.event;
    }

    public Tag(
        Integer id,
        Integer eid,
        String  value,
        String  event
    ) {
        this.id = id;
        this.eid = eid;
        this.value = value;
        this.event = event;
    }

    public Integer getId() {
        return this.id;
    }

    public Tag setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getEid() {
        return this.eid;
    }

    public Tag setEid(Integer eid) {
        this.eid = eid;
        return this;
    }

    public String getValue() {
        return this.value;
    }

    public Tag setValue(String value) {
        this.value = value;
        return this;
    }

    public String getEvent() {
        return this.event;
    }

    public Tag setEvent(String event) {
        this.event = event;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tag (");

        sb.append(id);
        sb.append(", ").append(eid);
        sb.append(", ").append(value);
        sb.append(", ").append(event);

        sb.append(")");
        return sb.toString();
    }

    public Tag(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public Tag fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getInteger("id"));
        setEid(json.getInteger("eid"));
        setValue(json.getString("value"));
        setEvent(json.getString("event"));
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("eid",getEid());
        json.put("value",getValue());
        json.put("event",getEvent());
        return json;
    }

}
