/*
 * This file is generated by jOOQ.
 */
package io.pet.spooch.database.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements VertxPojo, Serializable {

    private static final long serialVersionUID = -1066236391;

    private Integer id;
    private String  username;
    private String  password;
    private String  event;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.event = value.event;
    }

    public User(
        Integer id,
        String  username,
        String  password,
        String  event
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.event = event;
    }

    public Integer getId() {
        return this.id;
    }

    public User setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getUsername() {
        return this.username;
    }

    public User setUsername(String username) {
        this.username = username;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public User setPassword(String password) {
        this.password = password;
        return this;
    }

    public String getEvent() {
        return this.event;
    }

    public User setEvent(String event) {
        this.event = event;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(event);

        sb.append(")");
        return sb.toString();
    }

    public User(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public User fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getInteger("id"));
        setUsername(json.getString("username"));
        setPassword(json.getString("password"));
        setEvent(json.getString("event"));
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("username",getUsername());
        json.put("password",getPassword());
        json.put("event",getEvent());
        return json;
    }

}
