/*
 * This file is generated by jOOQ.
 */
package io.pet.spooch.database.tables.pojos;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements VertxPojo, Serializable {

    private static final long serialVersionUID = -259900193;

    private Integer id;
    private String  username;
    private String  password;
    private Integer eventid;
    private String  hash;
    private String  entityid;
    private Integer revision;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.eventid = value.eventid;
        this.hash = value.hash;
        this.entityid = value.entityid;
        this.revision = value.revision;
    }

    public User(
        Integer id,
        String  username,
        String  password,
        Integer eventid,
        String  hash,
        String  entityid,
        Integer revision
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.eventid = eventid;
        this.hash = hash;
        this.entityid = entityid;
        this.revision = revision;
    }

    public Integer getId() {
        return this.id;
    }

    public User setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getUsername() {
        return this.username;
    }

    public User setUsername(String username) {
        this.username = username;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public User setPassword(String password) {
        this.password = password;
        return this;
    }

    public Integer getEventid() {
        return this.eventid;
    }

    public User setEventid(Integer eventid) {
        this.eventid = eventid;
        return this;
    }

    public String getHash() {
        return this.hash;
    }

    public User setHash(String hash) {
        this.hash = hash;
        return this;
    }

    public String getEntityid() {
        return this.entityid;
    }

    public User setEntityid(String entityid) {
        this.entityid = entityid;
        return this;
    }

    public Integer getRevision() {
        return this.revision;
    }

    public User setRevision(Integer revision) {
        this.revision = revision;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(eventid);
        sb.append(", ").append(hash);
        sb.append(", ").append(entityid);
        sb.append(", ").append(revision);

        sb.append(")");
        return sb.toString();
    }

    public User(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public User fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getInteger("id"));
        setUsername(json.getString("username"));
        setPassword(json.getString("password"));
        setEventid(json.getInteger("eventId"));
        setHash(json.getString("hash"));
        setEntityid(json.getString("entityId"));
        setRevision(json.getInteger("revision"));
        return this;
    }


    @Override
    public io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("username",getUsername());
        json.put("password",getPassword());
        json.put("eventId",getEventid());
        json.put("hash",getHash());
        json.put("entityId",getEntityid());
        json.put("revision",getRevision());
        return json;
    }

}
